---
- name: Update the NTP
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:    
    - name: Update the NTP setting
      cisco.ios.ios_ntp_global:
        config:
          authenticate: true
          authentication_keys:
            - algorithm: md5
              encryption: 22
              id: 1
              key: <key goes here>
          servers:
            - server: 172.16.1.4  
              version: 2
        state: replaced
